accessibility:
  animations: true
appearance:
  dock: off
  dockScreen: current
  dockFill: 0.5
  dockSpace: 1
  dockHideOnBlur: false
  dockAlwaysOnTop: true
  flexTabs: false
  tabsLocation: top
  tabsInFullscreen: false
  cycleTabs: true
  theme: Follow the color scheme
  frame: thin
  css: '/* * { color: blue !important; } */'
  opacity: 1.0
  vibrancy: false
  vibrancyType: 'blur'
  lastTabClosesWindow: false
  spaciness: 1
  colorSchemeMode: 'dark'
  sideTabInactiveColor: ''
  sideTabHoverColor: ''
  sideTabActiveColor: ''
  sidePanelTextColor: ''
  sidePanelTextColorDark: ''
  sidePanelTextColorLight: ''
  sidePanelFontSize: 9
  sidePanelColors:
    __nonStructural: true
terminal:
  showBuiltinProfiles: true
  showRecentProfiles: 3
  paneResizeStep: 0.1
  focusFollowsMouse: false
  identification: null
codeEditor:
  # If set, Code Editor "Run in terminal" will open this profile ID (so you can give it a custom terminalColorScheme/theme)
  runProfile: null
hotkeys:
  profile:
    __nonStructural: true
  profile-selectors:
    __nonStructural: true
  group-selectors:
    __nonStructural: true
profiles: []
groups: []
profileDefaults:
  __nonStructural: true
  ssh:
    disableDynamicTitle: true
recoverTabs: true
enableAnalytics: true
enableWelcomeTab: true
electronFlags:
  - ['force_discrete_gpu', '0']
enableAutomaticUpdates: true
hideTray: false
version: 1
vault: null
encrypted: false
enableExperimentalFeatures: false
pluginBlacklist: []
commandBlacklist: []
providerBlacklist: []
profileBlacklist: []
hacks:
  disableGPU: false
  disableVibrancyWhileDragging: false
  enableFluentBackground: false
language: null
defaultQuickConnectProvider: "ssh"
